language: csharp
solution: htsl.sln
before_script:
  - nuget restore htsl.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release htsl.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./htslTest/bin/Release/htslTest.dll